using System.Linq;
using System.Numerics;
using Content.Client.Audio;
using Content.Client._Arcane.Radio;
using Content.Shared._Arcane.CCVars;
using Content.Shared._Arcane.CVars;
using Content.Shared.Radio;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Arcane.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSOptionsTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly SpriteSystem _sprites = default!;

    private static readonly Color SeparatorColor = Color.FromHex("#3D4059");

    public TTSOptionsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entitySystem.GetEntitySystem<SpriteSystem>();

        Control.AddOptionPercentSlider(
            ArtCVars.TTSVolume,
            SliderVolumeTTS,
            scale: ContentAudioSystem.TTSMultiplier);
        Control.AddOptionPercentSlider(
            ACCVars.TTSRadioVolume,
            SliderVolumeRadioTTS,
            scale: ContentAudioSystem.TTSRadioMultiplier);
        Control.AddOptionCheckBox(ACCVars.UseTTS, UseTTSCheckBox);

        PopulateChannelMixer();

        Control.Initialize();
    }

    private void PopulateChannelMixer()
    {
        AddChannelListHeader();

        var channels = _prototypes.EnumeratePrototypes<RadioChannelPrototype>()
            .Where(channel => channel.Frequency > 0)
            .OrderBy(channel => RadioChannelOrder.Channels.GetValueOrDefault(channel.ID, int.MaxValue))
            .ThenBy(channel => channel.Frequency)
            .ToList();

        for (var i = 0; i < channels.Count; i++)
        {
            AddChannelRow(channels[i]);
            if (i < channels.Count - 1)
                ChannelList.AddChild(MakeSeparator());
        }
    }

    private void AddChannelListHeader()
    {
        var header = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2),
        };

        header.AddChild(new Control { MinWidth = 36 });
        header.AddChild(new Label { Text = _loc.GetString("ui-options-tts-radio-channel"), MinWidth = 170, StyleClasses = { "LabelHeading" } });
        header.AddChild(new Label { Text = _loc.GetString("ui-options-tts-radio-channel-enabled"), MinWidth = 24, HorizontalAlignment = HAlignment.Center, StyleClasses = { "LabelHeading" } });
        header.AddChild(new Control { HorizontalExpand = true });
        header.AddChild(new Label { Text = _loc.GetString("ui-options-tts-radio-channel-volume"), StyleClasses = { "LabelHeading" } });
        ChannelList.AddChild(header);
    }

    private void AddChannelRow(RadioChannelPrototype channel)
    {
        var muted = TTSRadioChannelSettings.ParseMuted(_cfg.GetCVar(ACCVars.TTSRadioChannelMuted)).Contains(channel.Frequency);
        var volume = TTSRadioChannelSettings.ParseVolumes(_cfg.GetCVar(ACCVars.TTSRadioChannelVolumes)).GetValueOrDefault(channel.Frequency, 1f);

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 6, 0, 6),
            VerticalAlignment = VAlignment.Center,
        };

        var icon = new TextureRect
        {
            TextureScale = new Vector2(3, 3),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(4, 0, 4, 0),
        };
        if (_prototypes.TryIndex(channel.Icon, out var iconPrototype))
            icon.Texture = _sprites.Frame0(iconPrototype.Icon);
        row.AddChild(icon);

        var nameLabel = new Label
        {
            Text = _loc.GetString(channel.Name),
            MinWidth = 170,
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(nameLabel);

        var enabledCheckBox = new CheckBox
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MinWidth = 24,
            ToolTip = _loc.GetString("ui-options-tts-radio-channel-toggle-tooltip"),
        };
        row.AddChild(enabledCheckBox);

        var volumeSlider = new Slider
        {
            MinValue = 0f,
            MaxValue = 1f,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(volumeSlider);

        var volumeLabel = new Label
        {
            MinWidth = 40,
            Margin = new Thickness(6, 0, 0, 0),
            VerticalAlignment = VAlignment.Center,
        };
        row.AddChild(volumeLabel);

        enabledCheckBox.Pressed = !muted;
        volumeSlider.Value = volume;
        volumeLabel.Text = FormatPercent(volume);

        enabledCheckBox.OnToggled += _ =>
        {
            _cfg.SetCVar(ACCVars.TTSRadioChannelMuted,
                TTSRadioChannelSettings.FormatMutedToggle(
                    _cfg.GetCVar(ACCVars.TTSRadioChannelMuted), channel.Frequency, !enabledCheckBox.Pressed));
        };

        volumeSlider.OnValueChanged += _ =>
        {
            volumeLabel.Text = FormatPercent(volumeSlider.Value);
            _cfg.SetCVar(ACCVars.TTSRadioChannelVolumes,
                TTSRadioChannelSettings.UpsertVolume(
                    _cfg.GetCVar(ACCVars.TTSRadioChannelVolumes), channel.Frequency, volumeSlider.Value));
        };

        ChannelList.AddChild(row);
    }

    private static Control MakeSeparator()
    {
        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = SeparatorColor,
                ContentMarginBottomOverride = 2,
                ContentMarginLeftOverride = 2,
            },
            MinHeight = 1,
            Margin = new Thickness(0, 2, 0, 2),
        };
    }

    private string FormatPercent(float value)
    {
        return _loc.GetString("ui-options-value-percent", ("value", value));
    }
}