# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:RoleTimeRequirement # Goobstation
      role: JobBrigmedic
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
    - !type:SpeciesRequirement # Goob - None Felinid
      inverted: true
      species:
      - Felinid
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  guides: # goobstation
  - SpaceLaw
  - SOP-Security-Warden # Orion
  - SOP-Security # Orion
  goobcoins: 35 #Goob content
  salary: 90 # Orion
  payrollDepartmentAccount: Security # Orion
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff
  # Arcane-Start
  contracts:
  - DocumentContractEmploymentSecurity
  alternateTitles:
  - WardenDispatch
  - WardenJailer
  - WardenDungeonMaster
  # Arcane-End

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurityContraDetect # Goobstation
    id: WardenPDA
    ears: ClothingHeadsetAltWarden # Goobstation
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack

# Arcane-Start
- type: jobAlternateTitle
  id: WardenDispatch
  name: job-name-alt-warden-1

- type: jobAlternateTitle
  id: WardenJailer
  name: job-name-alt-warden-2

- type: jobAlternateTitle
  id: WardenDungeonMaster
  name: job-name-alt-warden-3
# Arcane-End
