# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 2.5h
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  guides: # goobstation
  - Atmospherics
  goobcoins: 20 #Goob content
  # Orion-Start
  salary: 85
  payrollDepartmentAccount: Engineering
  # Orion-End
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FirefighterDay
    prototype: FireAxe
  - !type:AddComponentSpecial # Goobstation
    components:
    - type: EngineeringStaff
  # Arcane-start
  contracts:
  - DocumentContractEmploymentEngineering
  alternateTitles:
  - AtmosphericTechnicianFirefighter
  - AtmosphericTechnicianEmergencyFireTech
  - AtmosphericTechnicianGasSynthesisTech
  - AtmosphericTechnicianLifeSupportTech
  # Arcane-end

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
#    eyes: ClothingEyesGlassesMeson # Orion-Edit: In loadout
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: AtmosphericTechnicianChameleonOutfit
  job: AtmosphericTechnician
  equipment:
    head: ClothingHeadHelmetAtmosFire
    mask: ClothingMaskGasAtmos
    neck: ClothingNeckScarfStripedLightBlue
    outerClothing: ClothingOuterSuitAtmosFire
    gloves: ClothingHandsGlovesColorYellow

# Arcane-Start
- type: jobAlternateTitle
  id: AtmosphericTechnicianFirefighter
  name: job-name-alt-atmos-1

- type: jobAlternateTitle
  id: AtmosphericTechnicianEmergencyFireTech
  name: job-name-alt-atmos-2

- type: jobAlternateTitle
  id: AtmosphericTechnicianGasSynthesisTech
  name: job-name-alt-atmos-3

- type: jobAlternateTitle
  id: AtmosphericTechnicianLifeSupportTech
  name: job-name-alt-atmos-4
# Arcane-End
