using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookToolbar : BoxContainer
{
    public GuidebookToolbar()
    {
        RobustXamlLoader.Load(this);
    }
}
