// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action? OnLoopToggled; // Orion
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    public event Action<float>? SetVolume; // Orion

    private EntityUid? _audio;

    private float _lockTimer;

    private bool _loopState; // Orion

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += _ =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += _ =>
        {
            OnStopPressed?.Invoke();
        };

        // Orion-Start
        LoopButton.OnPressed += _ =>
        {
            OnLoopToggled?.Invoke();
        };
        // Orion-Start

        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;
        VolumeSlider.OnReleased += VolumeSliderKeyUp; // Orion

        VolumeSlider.MaxValue = 100f; // Orion

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    // Arcane-Edit-Start
    // public JukeboxMenu(AudioSystem audioSystem)
    // {
    //     _audioSystem = audioSystem;
    // }
    // Arcane-Edit-End

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    // Orion-Start
    private void VolumeSliderKeyUp(Slider args)
    {
        SetVolume?.Invoke(VolumeSlider.Value);
        _lockTimer = 0.5f;
    }
    // Orion-End

    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        MusicList.Clear();

        foreach (var entry in jukeboxProtos)
        {
            MusicList.AddItem(entry.Name, metadata: entry.ID);
        }
        MusicList.SortItemsByText(); // Orion
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }

    // Orion-Start
    public void SetLoopButton(bool loopEnabled)
    {
        if (_loopState == loopEnabled)
            return;

        _loopState = loopEnabled;

        if (loopEnabled)
        {
            LoopButton.Text = Loc.GetString("jukebox-menu-button-loop-enabled");
            LoopButton.Pressed = true;
            return;
        }

        LoopButton.Text = Loc.GetString("jukebox-menu-button-loop");
        LoopButton.Pressed = false;
    }
    // Orion-End

    public void SetSelectedSong(string name, float length)
    {
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    // Orion-Start
    public void SetVolumeSlider(float volume)
    {
        VolumeSlider.Value = volume;
    }
    // Orion-End

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;
        VolumeSlider.Disabled = _lockTimer > 0f; // Orion

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            // Arcane-Start
            var length = PlaybackSlider.MaxValue;
            var position = audio.PlaybackPosition;

            if (length > 0f)
                position %= length;
            // Arcane-End

            DurationLabel.Text = $@"{TimeSpan.FromSeconds(position):mm\:ss} / {TimeSpan.FromSeconds(length):mm\:ss}"; // Arcane-Edit
        }
        else
        {
            DurationLabel.Text = $"00:00 / 00:00";
        }

        VolumeNumberLabel.Text = $"{VolumeSlider.Value:0.##} %"; // Orion

        if (PlaybackSlider.Grabbed)
            return;

        if (VolumeSlider.Grabbed) // Orion
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            // Arcane-Start
            var position = audio.PlaybackPosition;

            if (PlaybackSlider.MaxValue > 0f)
                position %= PlaybackSlider.MaxValue;
            // Arcane-End

            PlaybackSlider.SetValueWithoutEvent(position); // Arcane-Edit
        }
        else
        {
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }
}
