// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";
    // Arcane-Edit-Start
    public const string StylePropertyBorderColor = "borderColor";
    public const string StylePropertyBorderThickness = "borderThickness";
    // Arcane-Edit-End
    public const string NormalBgColor = "#313138";
    public const string HoverColor = "#3E6C45";

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex("#25252a"),
    };

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

        // Arcane-Edit-Start
        if (TryGetStyleProperty<Color>(StylePropertyBorderColor, out var borderColor))
            _styleBox.BorderColor = borderColor;

        if (TryGetStyleProperty<float>(StylePropertyBorderThickness, out var borderThickness))
            _styleBox.BorderThickness = new Thickness(borderThickness);
        // Arcane-Edit-End
    }
}
