// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Client._Arcane.StyleSheets; // Arcane
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            // Arcane-Edit-Start
            Chat.ChatWindowPanel.AddStyleClass(ArcaneStyleClass.LobbyChatSurface);
            Chat.Contents.AddStyleClass(ArcaneStyleClass.LobbyChatOutput);
            // Arcane-Edit-End
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text")); // Goobstation

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            // Orion-Start
            LeftCollapseButton.OnPressed += _ => ToggleLeftPanel(false);
            LeftExpandButton.OnPressed += _ => ToggleLeftPanel(true);

            TopCollapseButton.OnPressed += _ => ToggleTopPanel(false);
            TopExpandButton.OnPressed += _ => ToggleTopPanel(true);

            AttributionCollapseButton.OnPressed += _ => ToggleAttributionPanel(false);
            AttributionExpandButton.OnPressed += _ => ToggleAttributionPanel(true);
            // Orion-End
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    // Orion-Start
                    LeftSide.HorizontalExpand = false;
                    LayoutSpacer.Visible = true;
                    ExpandPanel.Visible = false;
                    TopPanel.Visible = true;
                    TopExpandPanel.Visible = false;
                    LeftInfoPanel.Visible = true;
                    LeftExpandPanel.Visible = false;
                    AttributionPanel.Visible = false;
                    AttributionExpandPanel.Visible = true;
                    // Orion-End
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    // Orion-Edit-Start
                    LeftSide.HorizontalExpand = true;
                    LayoutSpacer.Visible = false;
                    RightSide.Visible = false;
                    // Orion-Edit-End

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        // Orion-Start
        private void ToggleLeftPanel(bool value)
        {
            LeftInfoPanel.Visible = value;
            LeftExpandPanel.Visible = !value;
        }

        private void ToggleTopPanel(bool value)
        {
            TopPanel.Visible = value;
            TopExpandPanel.Visible = !value;
        }

        private void ToggleAttributionPanel(bool value)
        {
            AttributionPanel.Visible = value;
            AttributionExpandPanel.Visible = !value;
        }
        // Orion-End

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup,
        }
    }
}
