# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job # goob edit
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  goobcoins: 20 #Goob content
  # Orion-Start
  salary: 35
  payrollDepartmentAccount: Service
  # Orion-End
  access:
  - Maintenance
  special: # Goobstation
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - NanoTrasen
      - Assistant
  # Arcane-Start
  alternateTitles:
  - AssistantPassenger
  - AssistantVisitor
  - AssistantEntrepreneur
  - AssistantOffDuty
  - AssistantCivilian
  - AssistantFreelancer
  - AssistantTourist
  - AssistantTraveler
  # Arcane-End

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget

# Arcane-Start
- type: jobAlternateTitle
  id: AssistantPassenger
  name: job-name-alt-assistant-1

- type: jobAlternateTitle
  id: AssistantVisitor
  name: job-name-alt-assistant-2

- type: jobAlternateTitle
  id: AssistantEntrepreneur
  name: job-name-alt-assistant-3

- type: jobAlternateTitle
  id: AssistantOffDuty
  name: job-name-alt-assistant-4

- type: jobAlternateTitle
  id: AssistantCivilian
  name: job-name-alt-assistant-5

- type: jobAlternateTitle
  id: AssistantFreelancer
  name: job-name-alt-assistant-6

- type: jobAlternateTitle
  id: AssistantTourist
  name: job-name-alt-assistant-7

- type: jobAlternateTitle
  id: AssistantTraveler
  name: job-name-alt-assistant-8
# Arcane-End
