# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 2.5h
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-IAA # Arcane-Edit
  guides: # goobstation
  - SpaceLaw
#  - LegalSOP # Orion-Edit: Removed because dont have this SOP
  goobcoins: 10 #Goob content
  # Orion-Start
  salary: 50
  payrollDepartmentAccount: Service
  # Orion-End
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special: # Goobstation - Everyone knows lawyers are soulless.
  - !type:AddComponentSpecial
    components:
    - type: Condemned
      soulOwnedNotDevil: true
  # Arcane-start
  contracts:
  - DocumentContractEmploymentService
  alternateTitles:
  - LawyerAttorney
  - LawyerLegalRepresentative
  # Arcane-end

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLawyer # Arcane-Edit
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack

# Arcane-Start
- type: jobAlternateTitle
  id: LawyerAttorney
  name: job-name-alt-lawyer-1

- type: jobAlternateTitle
  id: LawyerLegalRepresentative
  name: job-name-alt-lawyer-2
# Arcane-End
