// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Diagnostics;
using System.Linq;
using Content.Client.Chemistry.EntitySystems;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookWindow : FancyWindow, ILinkClickHandler, IAnchorClickHandler
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IResourceManager _resourceManager = default!;

    private Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> _entries = new();

    private readonly ISawmill _sawmill;

    public ProtoId<GuideEntryPrototype> LastEntry;

    public GuidebookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("Guidebook");
        InitializeWorkspace(); // Arcane

        Tree.OnSelectedItemChanged += OnSelectionChanged;

        SearchBar.OnTextChanged += _ =>
        {
            HandleFilter();
        };
    }

    public void HandleClick(string link)
    {
        // Arcane-Edit-Start
        HandleWorkspaceLink(link);
    }

    private void SelectGuide(string link)
    {
        // Arcane-Edit-End
        if (!_entries.TryGetValue(link, out var entry))
            return;

        SelectEntryCategory(entry); // Arcane
        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            ShowGuide(entry);
    }

    public void HandleAnchor(IPrototypeLinkControl prototypeLinkControl)
    {
        var prototype = prototypeLinkControl.LinkedPrototype;
        if (prototype == null)
            return;

        var (linkableControls, _) = GetLinkableControlsAndLinks(EntryContainer);
        foreach (var linkableControl in linkableControls)
        {
            if (linkableControl.RepresentedPrototype != prototype)
                continue;

            if (linkableControl is not Control control)
                return;

            // Check if the target item is currently filtered out
            if (!control.Visible)
                control.Visible = true;

            UserInterfaceManager.DeferAction(() =>
            {
                if (control.GetControlScrollPosition() is not {} position)
                    return;

                Scroll.HScrollTarget = position.X;
                Scroll.VScrollTarget = position.Y;
            });

            break;
        }
    }

    private void OnSelectionChanged(TreeItem? item)
    {
        if (item != null && item.Metadata is GuideEntry entry)
        {
            ShowGuide(entry);

            var isRulesEntry = entry.RuleEntry;
            ReturnContainer.Visible = isRulesEntry;
            _ruleHomeEntry = entry.RuleEntry ? entry.Id : null; // Arcane-edit
        }
        else
            ClearSelectedGuide();
    }

    public void ClearSelectedGuide()
    {
        ClearWorkspaceArticle(); // Arcane
        Placeholder.Visible = true;
        EntryContainer.Visible = false;
        SearchContainer.Visible = false;
        EntryContainer.RemoveAllChildren();
    }

    private void ShowGuide(GuideEntry entry)
    {
        RememberArticleScroll(); // Arcane
        Scroll.SetScrollValue(default);
        Placeholder.Visible = false;
        EntryContainer.Visible = true;
        SearchBar.Text = "";
        EntryContainer.RemoveAllChildren();
        using var file = _resourceManager.ContentFileReadText(entry.Text);

        SearchContainer.Visible = entry.FilterEnabled;

        if (!_parsingMan.TryAddMarkup(EntryContainer, file.ReadToEnd()))
        {
            // The guidebook will automatically display the in-guidebook error if it fails

            _sawmill.Error($"Failed to parse contents of guide document {entry.Id}.");
        }

        LastEntry = entry.Id;
        RefreshWorkspaceArticle(entry); // Arcane

        var (linkableControls, linkControls) = GetLinkableControlsAndLinks(EntryContainer);

        HashSet<IPrototype> availablePrototypeLinks = new();
        foreach (var linkableControl in linkableControls)
        {
            var prototype = linkableControl.RepresentedPrototype;
            if (prototype != null)
                availablePrototypeLinks.Add(prototype);
        }

        foreach (var linkControl in linkControls)
        {
            var prototype = linkControl.LinkedPrototype;
            if (prototype != null && availablePrototypeLinks.Contains(prototype))
                linkControl.EnablePrototypeLink();
        }
    }

    public void UpdateGuides(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries = null,
        ProtoId<GuideEntryPrototype>? forceRoot = null,
        ProtoId<GuideEntryPrototype>? selected = null)
    {
        _entries = entries;
        UpdateWorkspaceGuides(rootEntries, forceRoot, selected); // Arcane-edit
    }

    private IEnumerable<GuideEntry> GetSortedEntries(List<ProtoId<GuideEntryPrototype>>? rootEntries)
    {
        if (rootEntries == null)
        {
            HashSet<ProtoId<GuideEntryPrototype>> entries = new(_entries.Keys);
            foreach (var entry in _entries.Values)
            {
                // Arcane-remove
                entries.ExceptWith(entry.Children);
            }

            rootEntries = entries.ToList();
        }

        return rootEntries
            .Where(_entries.ContainsKey) // Arcane
            .Select(rootEntryId => _entries[rootEntryId])
            .OrderBy(rootEntry => rootEntry.Priority)
            .ThenBy(rootEntry => Loc.GetString(rootEntry.Name));
    }

    private void RepopulateTree(List<ProtoId<GuideEntryPrototype>>? roots = null,
        ProtoId<GuideEntryPrototype>? forcedRoot = null)
    {
        Tree.Clear();

        HashSet<ProtoId<GuideEntryPrototype>> addedEntries = new();

        var parent = forcedRoot == null ? null : AddEntry(forcedRoot.Value, null, addedEntries);
        foreach (var entry in GetSortedEntries(roots))
        {
            AddEntry(entry.Id, parent, addedEntries);
        }

        Tree.SetAllExpanded(true);
    }

    private TreeItem? AddEntry(ProtoId<GuideEntryPrototype> id,
        TreeItem? parent,
        HashSet<ProtoId<GuideEntryPrototype>> addedEntries)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return null;

        if (!addedEntries.Add(id))
        {
            // TODO GUIDEBOOK Maybe allow duplicate entries?
            // E.g., for adding medicine under both chemicals & the chemist job
            Logger.Error($"Adding duplicate guide entry: {id}");
            return null;
        }

        var rulesProto = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        if (entry.RuleEntry && entry.Id != rulesProto.Id)
            return null;

        var item = Tree.AddItem(parent);
        item.Metadata = entry;
        var name = Loc.GetString(entry.Name);
        item.Label.Text = name;

        // Arcane-Edit-Start
        foreach (var child in GetSortedEntries(entry.Children))
        {
            AddEntry(child.Id, item, addedEntries);
        }
        // Arcane-Edit-End

        return item;
    }

    private void HandleFilter()
    {
        var emptySearch = SearchBar.Text.Trim().Length == 0;

        if (Tree.SelectedItem != null && Tree.SelectedItem.Metadata is GuideEntry entry && entry.FilterEnabled)
        {
            var foundElements = EntryContainer.GetSearchableControls();

            foreach (var element in foundElements)
            {
                element.SetHiddenState(true, SearchBar.Text.Trim());
            }
        }
    }

    private static (List<IPrototypeRepresentationControl>, List<IPrototypeLinkControl>) GetLinkableControlsAndLinks(Control parent)
    {
        List<IPrototypeRepresentationControl> linkableList = new();
        List<IPrototypeLinkControl> linkList = new();

        // Goobstation edit: iteration over recursion.
        // we have too many chems.
        var stack = new Stack<Control>();
        stack.Push(parent);

        while (stack.Count > 0)
        {
            var current = stack.Pop();

            foreach (var child in current.Children)
            {
                if (child is IPrototypeLinkControl linkChild)
                    linkList.Add(linkChild);

                if (child is IPrototypeRepresentationControl linkableChild)
                    linkableList.Add(linkableChild);

                if (child.ChildCount > 0)
                    stack.Push(child);
            }
        }
        // Goob edit end.

        return (linkableList, linkList);
    }
}
