using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client._Arcane.Radio;

[GenerateTypedNameReferences]
public sealed partial class HeadsetChannelWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private static readonly Color SeparatorColor = Color.FromHex("#3D4059");

    private readonly SpriteSystem _sprites = default!;

    /// <summary>
    ///     Raised when the player toggles receiving on a channel frequency.
    /// </summary>
    public Action<int, bool>? ChannelMuteToggled;

    public HeadsetChannelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entitySystem.GetEntitySystem<SpriteSystem>();
    }

    public void UpdateState(IEnumerable<ProtoId<RadioChannelPrototype>> channels, IReadOnlySet<int> mutedFrequencies)
    {
        ChannelList.RemoveAllChildren();

        var sorted = channels
            .Where(id => _prototypes.TryIndex(id, out _))
            .Select(_prototypes.Index)
            .OrderBy(channel => RadioChannelOrder.Channels.GetValueOrDefault(channel.ID, int.MaxValue))
            .ThenBy(channel => channel.Frequency)
            .ToList();

        for (var i = 0; i < sorted.Count; i++)
        {
            AddChannelRow(sorted[i], mutedFrequencies);
            if (i < sorted.Count - 1)
                ChannelList.AddChild(MakeSeparator());
        }
    }

    private void AddChannelRow(RadioChannelPrototype channel, IReadOnlySet<int> mutedFrequencies)
    {
        var muted = mutedFrequencies.Contains(channel.Frequency);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 6, 0, 6),
            VerticalAlignment = VAlignment.Center,
        };

        var icon = new TextureRect
        {
            TextureScale = new Vector2(3, 3),
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(4, 0, 8, 0),
        };
        if (_prototypes.TryIndex(channel.Icon, out var iconPrototype))
            icon.Texture = _sprites.Frame0(iconPrototype.Icon);
        row.AddChild(icon);

        row.AddChild(new Label
        {
            Text = _loc.GetString(channel.Name),
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });

        var enableCheckBox = new CheckBox
        {
            VerticalAlignment = VAlignment.Center,
            ToolTip = _loc.GetString("headset-channel-mute-tooltip"),
        };
        row.AddChild(enableCheckBox);

        var frequency = channel.Frequency;
        enableCheckBox.Pressed = !muted;
        enableCheckBox.OnToggled += _ => ChannelMuteToggled?.Invoke(frequency, !enableCheckBox.Pressed);

        ChannelList.AddChild(row);
    }

    private static Control MakeSeparator()
    {
        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = SeparatorColor,
                ContentMarginBottomOverride = 2,
                ContentMarginLeftOverride = 2,
            },
            MinHeight = 1,
            Margin = new Thickness(0, 2, 0, 2),
        };
    }
}